### ISSUE TITLE
the bot works prefectly but now i have this error....

### ISSUE THREAD

**Issue by pakoS90** [morrolinux/subito-it-searcher#36]
C:\Users\IoSonoLeggenda\Desktop\subito>python subito-searcher.py --refresh
Traceback (most recent call last):
  File "C:\Users\IoSonoLeggenda\Desktop\subito\subito-searcher.py", line 294, in <module>
    load_queries()
  File "C:\Users\IoSonoLeggenda\Desktop\subito\subito-searcher.py", line 61, in load_queries
    queries = json.load(file)
  File "C:\Users\IoSonoLeggenda\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\IoSonoLeggenda\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\IoSonoLeggenda\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\IoSonoLeggenda\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by EspyyJavaw** [comment]
Hi, are you still encountering this error? It seems that the issue might be related to the `searches.tracked` file. Let me know if you still need help :)
