### ISSUE TITLE
Impossibile aggiungere prodotti da tracciare

### ISSUE THREAD

**Issue by Kqppah** [morrolinux/subito-it-searcher#38]
Quando inserisco una nuovo prodotto mi dà un errore penso inerente a --minPrice e --maxPrice. Se invio il comando senza quelli due valori, la query viene inserita normalmente. Problema riscontrato sia su Win 7 che su Win 10. Qualche mese fa funzionava, non è che stata cambiata qualcosa nel codice? Sapete come potrei risolvere? (Premetto che non so programmare)

**Comment by Kqppah** [comment]
Attualmente ho risolto utilizzando la versione precedente del bot

**Comment by jaco-99** [comment]
Ciao, potresti riportare l'errore che ti viene mostrato o la query che lo genera?

**Comment by Kqppah** [comment]
> Ciao, potresti riportare l'errore che ti viene mostrato o la query che lo genera?
Ho provato anche con la versione di 3 settimane fa e continua a darmi questo errore, se rimuovo minPrice e  maxPrice la query va, ma ovviamente perde la sua utilità. Quindi attualmente continuo ad utilizzare una versione precedente del bot.

python3 subito-searcher.py --add RTX_2060_Super --url https://www.subito.it/annunci-italia/vendita/elettronica/?q=2060+super --minPrice 0 --maxPrice 110

2024-12-28, 23:14:51 running query ("RTX_2060_Super" - https://www.subito.it/annunci-italia/vendita/elettronica/?q=2060+super)...
Traceback (most recent call last):
  File "/home/computerino/Desktop/SubitoSearcher/subito-searcher.py", line 324, in <module>
    run_query(args.url, args.name, False, args.minPrice if args.minPrice is not None else "null", args.maxPrice if args.maxPrice is not None else "null",)
  File "/home/computerino/Desktop/SubitoSearcher/subito-searcher.py", line 205, in run_query
    if queries.get(name).get(url).get(minPrice).get(maxPrice).get(link):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Kqppah** [comment]
> Ciao, potresti riportare l'errore che ti viene mostrato o la query che lo genera?

Ho provato anche con la versione di 3 settimane fa e continua a darmi questo errore, se rimuovo minPrice e maxPrice la query va, ma ovviamente perde la sua utilità. Quindi attualmente continuo ad utilizzare una versione precedente del bot.

python3 subito-searcher.py --add RTX_2060_Super --url https://www.subito.it/annunci-italia/vendita/elettronica/?q=2060+super --minPrice 0 --maxPrice 110

2024-12-28, 23:14:51 running query ("RTX_2060_Super" - https://www.subito.it/annunci-italia/vendita/elettronica/?q=2060+super)...
Traceback (most recent call last):
File "/home/computerino/Desktop/SubitoSearcher/subito-searcher.py", line 324, in
run_query(args.url, args.name, False, args.minPrice if args.minPrice is not None else "null", args.maxPrice if args.maxPrice is not None else "null",)
File "/home/computerino/Desktop/SubitoSearcher/subito-searcher.py", line 205, in run_query
if queries.get(name).get(url).get(minPrice).get(maxPrice).get(link):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dmaz-85** [comment]
Ciao anchio sto rilevando credo lo stesso errore con la seguente ricerca:
python subito-searcher.py --add "terraforming mars" --url https://www.subito.it/annunci-italia/vendita/usato/\?q\="terraforming+mars" --minPrice 10 --maxPrice 40

La ricerca funziona se rimuovo il range di price oppure se cambio leggermente la stringa, usando "terraformin+mars" al posto di "terraforming+mars". (ho tolto una "g")
Ho rilevato questo comportamento anche su altre ricerche dove cambiando qualche carattere dell'oggetto di ricerca questa va a buon fine o restituisce l'errore di cui sopra.

**Comment by jaco-99** [comment]
Il problema dovrebbe essere stato risolto nella PR #43.
Bisogna aspettare che venga valutata e nel caso approvata.
